In [1]:
import sys
import os
script_dir = os.getcwd()
sys.path.append(script_dir)

In [2]:
import pandas as pd
from collections import Counter
import numpy as np

from tensorflow.keras import layers, models

In [ ]:
def create_MLP_model(input_dim, output_dim, dense_layers):
    model = models.Sequential()
    
    # Redimensionar os dados de entrada
    model.add(layers.Reshape((input_dim,), input_shape=(input_dim, 1)))
    
    model.add(layers.Dense(dense_layers[0], activation='relu'))

    for neurons in dense_layers[1:]:
        model.add(layers.Dense(neurons, activation='relu'))

    model.add(layers.Dense(output_dim, activation='softmax'))

    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    return model

In [38]:
csvdata = pd.read_csv(r'Data\regular_alt_batteries\battery22.csv', low_memory=False)

In [4]:
csvdata

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
0,2022-11-26 09:49:00,0.000,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
1,2022-11-26 09:49:00,0.349,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
2,2022-11-26 09:49:00,0.496,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
3,2022-11-26 09:49:00,0.935,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
4,2022-11-26 09:49:00,1.843,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2069662,2023-01-22 11:35:00,2095705.687,0.0,12.169,22.293,NaN,NaN,NaN,NaN,NaN
2069663,2023-01-22 11:35:00,2095706.713,0.0,12.169,22.289,NaN,NaN,NaN,NaN,NaN
2069664,2023-01-22 11:35:00,2095707.743,0.0,12.168,22.293,NaN,NaN,NaN,NaN,NaN
2069665,2023-01-22 11:35:00,2095708.770,0.0,12.168,22.293,NaN,NaN,NaN,NaN,NaN
2069666,2023-01-22 11:35:00,2095709.830,0.0,12.169,22.293,NaN,NaN,NaN,NaN,NaN

In [5]:
casa = csvdata[csvdata['start_time'] == "2022-11-26 09:49:00"]
casa.head(20)

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
0,2022-11-26 09:49:00,0.000,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
1,2022-11-26 09:49:00,0.349,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
2,2022-11-26 09:49:00,0.496,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
3,2022-11-26 09:49:00,0.935,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
4,2022-11-26 09:49:00,1.843,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
5,2022-11-26 09:49:00,2.751,0.0,8.365,22.614,NaN,NaN,NaN,NaN,NaN
6,2022-11-26 09:49:00,3.660,0.0,8.364,22.614,NaN,NaN,NaN,NaN,NaN
7,2022-11-26 09:49:00,4.568,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
8,2022-11-26 09:49:00,5.476,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
9,2022-11-26 09:49:00,6.385,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
10,2022-11-26 09:49:00,7.313,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
11,2022-11-26 09:49:00,8.223,0.0,8.364,22.611,NaN,NaN,NaN,NaN,NaN
12,2022-11-26 09:49:00,9.133,0.0,8.364,22.611,NaN,NaN,NaN,NaN,NaN
13,2022-11-26 09:49:00,10.042,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
14,2022-11-26 09:49:00,10.951,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
15,2022-11-26 09:49:00,11.863,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
16,2022-11-26 09:49:00,12.772,0.0,8.364,22.611,NaN,NaN,NaN,NaN,NaN
17,2022-11-26 09:49:00,13.681,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
18,2022-11-26 09:49:00,14.591,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
19,2022-11-26 09:49:00,15.521,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN

In [24]:
Valor_modo_real = csvdata['temperature_battery']
start_times = Valor_modo_real.unique()
areas_number = len(start_times)
areas_number

12157

In [8]:
Counter(Valor_modo_real)

Counter({0.0: 720269, -1.0: 260562, 1.0: 1088836})

In [9]:
Tropa_do_gera = []
qtd_contada = 0
momento = Valor_modo_real[0]

for modo in range(len(Valor_modo_real)):
    if momento == Valor_modo_real[modo]:
        qtd_contada += 1
    else:
        Tropa_do_gera.append([momento, qtd_contada])
        momento = Valor_modo_real[modo]
        qtd_contada = 1

    if modo == len(Valor_modo_real) - 1:
        Tropa_do_gera.append([momento, qtd_contada])

In [10]:
Tropa_do_gera

[[0.0, 653],
 [-1.0, 3756],
 [0.0, 623],
 [1.0, 3170],
 [0.0, 635],
 [-1.0, 571],
 [0.0, 627],
 [1.0, 3225],
 [0.0, 141],
 [-1.0, 583],
 [0.0, 644],
 [1.0, 3283],
 [0.0, 625],
 [-1.0, 562],
 [0.0, 14],
 [1.0, 3312],
 [0.0, 756],
 [-1.0, 564],
 [0.0, 625],
 [1.0, 3231],
 [0.0, 631],
 [-1.0, 567],
 [0.0, 620],
 [1.0, 3222],
 [0.0, 628],
 [-1.0, 564],
 [0.0, 622],
 [1.0, 3181],
 [0.0, 620],
 [-1.0, 556],
 [0.0, 615],
 [1.0, 3126],
 [0.0, 615],
 [-1.0, 547],
 [0.0, 613],
 [1.0, 3108],
 [0.0, 2941],
 [-1.0, 533],
 [0.0, 599],
 [1.0, 3051],
 [0.0, 596],
 [-1.0, 530],
 [0.0, 600],
 [1.0, 3038],
 [0.0, 596],
 [-1.0, 528],
 [0.0, 585],
 [1.0, 2982],
 [0.0, 588],
 [-1.0, 521],
 [0.0, 587],
 [1.0, 2973],
 [0.0, 588],
 [-1.0, 519],
 [0.0, 580],
 [1.0, 2889],
 [0.0, 571],
 [-1.0, 503],
 [0.0, 568],
 [1.0, 2868],
 [0.0, 567],
 [-1.0, 501],
 [0.0, 565],
 [1.0, 2817],
 [0.0, 551],
 [-1.0, 486],
 [0.0, 559],
 [1.0, 2809],
 [0.0, 4081],
 [-1.0, 557],
 [0.0, 633],
 [1.0, 3180],
 [0.0, 625],
 [-1.0, 545],
 [0.0, 622],
 [1.0, 3132],
 [0.0, 255],
 [-1.0, 553],
 [0.0, 634],
 [1.0, 3145],
 [0.0, 1185],
 [-1.0, 537],
 [0.0, 614],
 [1.0, 3101],
 [0.0, 610],
 [-1.0, 3470],
 [0.0, 617],
 [1.0, 2990],
 [0.0, 614],
 [-1.0, 532],
 [0.0, 608],
 [1.0, 3002],
 [0.0, 603],
 [-1.0, 524],
 [0.0, 601],
 [1.0, 2984],
 [0.0, 599],
 [-1.0, 520],
 [0.0, 598],
 [1.0, 2949],
 [0.0, 590],
 [-1.0, 515],
 [0.0, 588],
 [1.0, 2906],
 [0.0, 587],
 [-1.0, 510],
 [0.0, 587],
 [1.0, 2902],
 [0.0, 577],
 [-1.0, 500],
 [0.0, 577],
 [1.0, 2865],
 [0.0, 570],
 [-1.0, 499],
 [0.0, 577],
 [1.0, 2859],
 [0.0, 570],
 [-1.0, 488],
 [0.0, 564],
 [1.0, 2805],
 [0.0, 2627],
 [-1.0, 488],
 [0.0, 567],
 [1.0, 2785],
 [0.0, 552],
 [-1.0, 477],
 [0.0, 553],
 [1.0, 2752],
 [0.0, 4420],
 [-1.0, 538],
 [0.0, 631],
 [1.0, 3097],
 [0.0, 616],
 [-1.0, 526],
 [0.0, 614],
 [1.0, 3051],
 [0.0, 616],
 [-1.0, 523],
 [0.0, 618],
 [1.0, 3039],
 [0.0, 619],
 [-1.0, 523],
 [0.0, 608],
 [1.0, 3000],
 [0.0, 610],
 [-1.0, 519],
 [0.0, 600],
 [1.0, 2956],
 [0.0, 603],
 [-1.0, 515],
 [0.0, 602],
 [1.0, 2932],
 [0.0, 598],
 [-1.0, 513],
 [0.0, 597],
 [1.0, 2889],
 [0.0, 590],
 [-1.0, 502],
 [0.0, 588],
 [1.0, 2858],
 [0.0, 963],
 [-1.0, 501],
 [0.0, 588],
 [1.0, 2833],
 [0.0, 575],
 [-1.0, 493],
 [0.0, 580],
 [1.0, 2806],
 [0.0, 576],
 [-1.0, 3164],
 [0.0, 565],
 [1.0, 2721],
 [0.0, 569],
 [-1.0, 481],
 [0.0, 567],
 [1.0, 2751],
 [0.0, 568],
 [-1.0, 479],
 [0.0, 566],
 [1.0, 2707],
 [0.0, 554],
 [-1.0, 468],
 [0.0, 560],
 [1.0, 3331],
 [0.0, 920],
 [1.0, 3063],
 [0.0, 973],
 [-1.0, 520],
 [0.0, 612],
 [1.0, 3001],
 [0.0, 620],
 [-1.0, 518],
 [0.0, 612],
 [1.0, 2993],
 [0.0, 615],
 [-1.0, 520],
 [0.0, 615],
 [1.0, 2955],
 [0.0, 612],
 [-1.0, 513],
 [0.0, 606],
 [1.0, 2909],
 [0.0, 2979],
 [-1.0, 504],
 [0.0, 597],
 [1.0, 2896],
 [0.0, 591],
 [-1.0, 495],
 [0.0, 587],
 [1.0, 2847],
 [0.0, 588],
 [-1.0, 490],
 [0.0, 578],
 [1.0, 2831],
 [0.0, 587],
 [-1.0, 492],
 [0.0, 582],
 [1.0, 2771],
 [0.0, 582],
 [-1.0, 482],
 [0.0, 577],
 [1.0, 2763],
 [0.0, 578],
 [-1.0, 481],
 [0.0, 576],
 [1.0, 2744],
 [0.0, 567],
 [-1.0, 471],
 [0.0, 567],
 [1.0, 2719],
 [0.0, 562],
 [-1.0, 475],
 [0.0, 567],
 [1.0, 2716],
 [0.0, 554],
 [-1.0, 459],
 [0.0, 550],
 [1.0, 2659],
 [0.0, 558],
 [-1.0, 463],
 [0.0, 552],
 [1.0, 2644],
 [0.0, 891],
 [-1.0, 462],
 [0.0, 550],
 [1.0, 2586],
 [0.0, 547],
 [-1.0, 455],
 [0.0, 550],
 [1.0, 2604],
 [0.0, 1323],
 [-1.0, 518],
 [0.0, 633],
 [1.0, 2989],
 [0.0, 614],
 [-1.0, 3313],
 [0.0, 621],
 [1.0, 2896],
 [0.0, 617],
 [-1.0, 509],
 [0.0, 616],
 [1.0, 2910],
 [0.0, 610],
 [-1.0, 503],
 [0.0, 610],
 [1.0, 2870],
 [0.0, 601],
 [-1.0, 499],
 [0.0, 601],
 [1.0, 2849],
 [0.0, 600],
 [-1.0, 492],
 [0.0, 597],
 [1.0, 2819],
 [0.0, 588],
 [-1.0, 484],
 [0.0, 589],
 [1.0, 2794],
 [0.0, 582],
 [-1.0, 476],
 [0.0, 588],
 [1.0, 2781],
 [0.0, 589],
 [-1.0, 479],
 [0.0, 580],
 [1.0, 2742],
 [0.0, 579],
 [-1.0, 473],
 [0.0, 575],
 [1.0, 2700],
 [0.0, 929],
 [-1.0, 473],
 [0.0, 579],
 [1.0, 3421],
 [0.0, 574],
 [-1.0, 3],
 [0.0, 570],
 [1.0, 941],
 [0.0, 1],
 [1.0, 2973],
 [0.0, 629],
 [-1.0, 504],
 [0.0, 614],
 [1.0, 2901],
 [0.0, 623],
 [-1.0, 507],
 [0.0, 618],
 [1.0, 2892],
 [0.0, 618],
 [-1.0, 501],
 [0.0, 619],
 [1.0, 2869],
 [0.0, 612],
 [-1.0, 497],
 [0.0, 614],
 [1.0, 2831],
 [0.0, 605],
 [-1.0, 490],
 [0.0, 605],
 [1.0, 2826],
 [0.0, 2474],
 [-1.0, 515],
 [0.0, 630],
 [1.0, 2952],
 [0.0, 616],
 [-1.0, 498],
 [0.0, 615],
 [1.0, 2904],
 [0.0, 617],
 [-1.0, 496],
 [0.0, 613],
 [1.0, 2893],
 [0.0, 618],
 [-1.0, 501],
 [0.0, 612],
 [1.0, 2851],
 [0.0, 614],
 [-1.0, 493],
 [0.0, 607],
 [1.0, 2802],
 [0.0, 4656],
 [-1.0, 483],
 [0.0, 597],
 [1.0, 2682],
 [0.0, 634],
 [-1.0, 3276],
 [0.0, 613],
 [1.0, 2864],
 [0.0, 621],
 [-1.0, 502],
 [0.0, 615],
 [1.0, 2872],
 [0.0, 618],
 [-1.0, 499],
 [0.0, 619],
 [1.0, 2842],
 [0.0, 611],
 [-1.0, 493],
 [0.0, 613],
 [1.0, 2798],
 [0.0, 608],
 [-1.0, 487],
 [0.0, 606],
 [1.0, 2791],
 [0.0, 1822],
 [-1.0, 483],
 [0.0, 599],
 [1.0, 2748],
 [0.0, 589],
 [-1.0, 479],
 [0.0, 591],
 [1.0, 2725],
 [0.0, 587],
 [-1.0, 472],
 [0.0, 590],
 [1.0, 2720],
 [0.0, 580],
 [-1.0, 466],
 [0.0, 583],
 [1.0, 2681],
 [0.0, 2861],
 [-1.0, 462],
 [0.0, 575],
 [1.0, 2656],
 [0.0, 1639],
 [-1.0, 505],
 [0.0, 628],
 [1.0, 2898],
 [0.0, 614],
 [-1.0, 489],
 [0.0, 612],
 [1.0, 2852],
 [0.0, 620],
 [-1.0, 487],
 [0.0, 613],
 [1.0, 2832],
 [0.0, 616],
 [-1.0, 490],
 [0.0, 615],
 [1.0, 2806],
 [0.0, 613],
 [-1.0, 485],
 [0.0, 610],
 [1.0, 2759],
 [0.0, 601],
 [-1.0, 478],
 [0.0, 603],
 [1.0, 2746],
 [0.0, 599],
 [-1.0, 476],
 [0.0, 599],
 [1.0, 2724],
 [0.0, 586],
 [-1.0, 467],
 [0.0, 593],
 [1.0, 2689],
 [0.0, 586],
 [-1.0, 468],
 [0.0, 589],
 [1.0, 2690],
 [0.0, 821],
 [-1.0, 456],
 [0.0, 576],
 [1.0, 2642],
 [0.0, 2987],
 [-1.0, 458],
 [0.0, 578],
 [1.0, 2619],
 [0.0, 823],
 [-1.0, 2944],
 [0.0, 560],
 [1.0, 2575],
 [0.0, 565],
 [-1.0, 447],
 [0.0, 566],
 [1.0, 2553],
 [0.0, 557],
 [-1.0, 440],
 [0.0, 563],
 [1.0, 2523],
 [0.0, 552],
 [-1.0, 436],
 [0.0, 554],
 [1.0, 2514],
 [0.0, 3968],
 [-1.0, 496],
 [0.0, 628],
 [1.0, 2844],
 [0.0, 3464],
 [-1.0, 487],
 [0.0, 618],
 [1.0, 2793],
 [0.0, 682],
 [-1.0, 484],
 [0.0, 615],
 [1.0, 2780],
 [0.0, 667],
 [-1.0, 479],
 [0.0, 611],
 [1.0, 2746],
 [0.0, 658],
 [-1.0, 473],
 [0.0, 605],
 [1.0, 2714],
 [0.0, 657],
 [-1.0, 470],
 [0.0, 601],
 [1.0, 2713],
 [0.0, 3083],
 [-1.0, 459],
 [0.0, 587],
 [1.0, 2646],
 [0.0, 651],
 [-1.0, 460],
 [0.0, 587],
 [1.0, 2652],
 [0.0, 637],
 [-1.0, 455],
 [0.0, 584],
 [1.0, 2610],
 [0.0, 627],
 [-1.0, 444],
 [0.0, 579],
 [1.0, 2602],
 [0.0, 636],
 [-1.0, 447],
 [0.0, 572],
 [1.0, 2574],
 [0.0, 628],
 [-1.0, 443],
 [0.0, 564],
 [1.0, 2541],
 [0.0, 621],
 [-1.0, 441],
 [0.0, 567],
 [1.0, 2529],
 [0.0, 618],
 [-1.0, 434],
 [0.0, 561],
 [1.0, 2496],
 [0.0, 611],
 [-1.0, 432],
 [0.0, 555],
 [1.0, 2483],
 [0.0, 843],
 [-1.0, 426],
 [0.0, 550],
 [1.0, 2466],
 [0.0, 7759],
 [-1.0, 3193],
 [0.0, 621],
 [1.0, 2750],
 [0.0, 623],
 [-1.0, 595],
 [0.0, 621],
 [1.0, 2767],
 [0.0, 615],
 [-1.0, 588],
 [0.0, 615],
 [1.0, 2757],
 [0.0, 215],
 [-1.0, 603],
 [0.0, 636],
 [1.0, 2821],
 [0.0, 612],
 [-1.0, 584],
 [0.0, 615],
 [1.0, 2776],
 [0.0, 615],
 [-1.0, 583],
 [0.0, 613],
 [1.0, 2767],
 [0.0, 614],
 [-1.0, 587],
 [0.0, 612],
 [1.0, 2728],
 [0.0, 2435],
 [-1.0, 569],
 [0.0, 598],
 [1.0, 2690],
 [0.0, 593],
 [-1.0, 566],
 [0.0, 599],
 [1.0, 2675],
 [0.0, 599],
 [-1.0, 559],
 [0.0, 589],
 [1.0, 2630],
 [0.0, 587],
 [-1.0, 558],
 [0.0, 586],
 [1.0, 2613],
 [0.0, 2790],
 [-1.0, 551],
 [0.0, 580],
 [1.0, 2593],
 [0.0, 575],
 [-1.0, 541],
 [0.0, 569],
 [1.0, 2571],
 [0.0, 575],
 [-1.0, 546],
 [0.0, 576],
 [1.0, 2541],
 [0.0, 568],
 [-1.0, 541],
 [0.0, 570],
 [1.0, 1889],
 [0.0, 624],
 [1.0, 2822],
 [0.0, 631],
 [-1.0, 588],
 [0.0, 610],
 [1.0, 2742],
 [0.0, 623],
 [-1.0, 586],
 [0.0, 621],
 [1.0, 2737],
 [0.0, 617],
 [-1.0, 582],
 [0.0, 618],
 [1.0, 2715],
 [0.0, 609],
 [-1.0, 575],
 [0.0, 615],
 [1.0, 2683],
 [0.0, 601],
 [-1.0, 570],
 [0.0, 604],
 [1.0, 2668],
 [0.0, 598],
 [-1.0, 564],
 [0.0, 600],
 [1.0, 2650],
 [0.0, 2114],
 [-1.0, 557],
 [0.0, 590],
 [1.0, 2591],
 [0.0, 812],
 [-1.0, 2952],
 [0.0, 580],
 [1.0, 2575],
 [0.0, 582],
 [-1.0, 543],
 [0.0, 577],
 [1.0, 2539],
 [0.0, 577],
 [-1.0, 541],
 [0.0, 577],
 [1.0, 2537],
 [0.0, 571],
 [-1.0, 536],
 [0.0, 573],
 [1.0, 2507],
 [0.0, 559],
 [-1.0, 525],
 [0.0, 571],
 [1.0, 2498],
 [0.0, 565],
 [-1.0, 524],
 [0.0, 561],
 [1.0, 2462],
 [0.0, 1834],
 [-1.0, 514],
 [0.0, 548],
 [1.0, 2444],
 [0.0, 551],
 [-1.0, 518],
 [0.0, 547],
 [1.0, 2417],
 [0.0, 548],
 [-1.0, 512],
 [0.0, 547],
 [1.0, 2394],
 [0.0, 4513],
 [-1.0, 590],
 [0.0, 631],
 [1.0, 2770],
 [0.0, 613],
 [-1.0, 572],
 [0.0, 611],
 [1.0, 2716],
 [0.0, 1578],
 [-1.0, 573],
 [0.0, 616],
 [1.0, 2715],
 [0.0, 612],
 [-1.0, 569],
 [0.0, 610],
 [1.0, 2686],
 [0.0, 607],
 [-1.0, 560],
 [0.0, 601],
 [1.0, 2646],
 [0.0, 601],
 [-1.0, 560],
 [0.0, 598],
 [1.0, 2626],
 [0.0, 597],
 [-1.0, 556],
 [0.0, 604],
 [1.0, 2587],
 [0.0, 588],
 [-1.0, 550],
 [0.0, 591],
 [1.0, 2566],
 [0.0, 587],
 [-1.0, 545],
 [0.0, 590],
 [1.0, 2570],
 [0.0, 584],
 [-1.0, 542],
 [0.0, 586],
 [1.0, 2543],
 [0.0, 569],
 [-1.0, 528],
 [0.0, 571],
 [1.0, 2528],
 [0.0, 2823],
 [-1.0, 529],
 [0.0, 573],
 [1.0, 2482],
 [0.0, 794],
 [-1.0, 2814],
 [0.0, 565],
 [1.0, 2464],
 [0.0, 559],
 [-1.0, 517],
 [0.0, 561],
 [1.0, 2430],
 [0.0, 551],
 [-1.0, 515],
 [0.0, 556],
 [1.0, 2423],
 [0.0, 552],
 [-1.0, 507],
 [0.0, 550],
 [1.0, 2398],
 [0.0, 5890],
 [-1.0, 553],
 [0.0, 629],
 [1.0, 2743],
 [0.0, 610],
 [-1.0, 566],
 [0.0, 613],
 [1.0, 2697],
 [0.0, 618],
 [-1.0, 566],
 [0.0, 612],
 [1.0, 2682],
 [0.0, 614],
 [-1.0, 566],
 [0.0, 616],
 [1.0, 2651],
 [0.0, 611],
 [-1.0, 561],
 [0.0, 612],
 [1.0, 2719],
 [0.0, 1899],
 [-1.0, 564],
 [0.0, 609],
 [1.0, 2692],
 [0.0, 2629],
 [-1.0, 566],
 [0.0, 615],
 [1.0, 2675],
 [0.0, 3050],
 [-1.0, 559],
 [0.0, 605],
 [1.0, 2610],
 [0.0, 599],
 [-1.0, 551],
 [0.0, 601],
 [1.0, 2593],
 [0.0, 597],
 [-1.0, 549],
 [0.0, 600],
 [1.0, 5239],
 [0.0, 631],
 [-1.0, 570],
 [0.0, 611],
 [1.0, 2669],
 [0.0, 621],
 [-1.0, 570],
 [0.0, 620],
 [1.0, 2666],
 [0.0, 615],
 [-1.0, 564],
 [0.0, 617],
 [1.0, 2658],
 [0.0, 609],
 [-1.0, 559],
 [0.0, 612],
 [1.0, 2632],
 [0.0, 601],
 [-1.0, 553],
 [0.0, 602],
 [1.0, 2610],
 [0.0, 602],
 [-1.0, 547],
 [0.0, 601],
 [1.0, 2602],
 [0.0, 897],
 [-1.0, 542],
 [0.0, 590],
 [1.0, 2022],
 [0.0, 640],
 [1.0, 474],
 [0.0, 634],
 [-1.0, 3029],
 [0.0, 611],
 [1.0, 6378],
 [0.0, 1703],
 [-1.0, 559],
 [0.0, 615],
 [1.0, 2670],
 [0.0, 912],
 [-1.0, 558],
 [0.0, 614],
 [1.0, 2667],
 [0.0, 880],
 [-1.0, 563],
 [0.0, 611],
 [1.0, 2630],
 [0.0, 871],
 [-1.0, 556],
 [0.0, 603],
 [1.0, 2595],
 [0.0, 857],
 [-1.0, 550],
 [0.0, 603],
 [1.0, 2582],
 [0.0, 852],
 [-1.0, 545],
 [0.0, 603],
 [1.0, 4839],
 [0.0, 632],
 [-1.0, 565],
 [0.0, 610],
 [1.0, 2650],
 [0.0, 622],
 [-1.0, 565],
 [0.0, 620],
 [1.0, 2643],
 [0.0, 616],
 [-1.0, 559],
 [0.0, 616],
 [1.0, 2626],
 [0.0, 1845],
 [-1.0, 554],
 [0.0, 607],
 [1.0, 2583],
 [0.0, 600],
 [-1.0, 545],
 [0.0, 601],
 [1.0, 2570],
 [0.0, 595],
 [-1.0, 544],
 [0.0, 600],
 [1.0, 2556],
 [0.0, 585],
 [-1.0, 533],
 [0.0, 589],
 [1.0, 2524],
 [0.0, 1637],
 [-1.0, 533],
 [0.0, 585],
 [1.0, 2521],
 [0.0, 1243],
 [-1.0, 573],
 [0.0, 631],
 [1.0, 2678],
 [0.0, 610],
 [-1.0, 555],
 [0.0, 613],
 [1.0, 2655],
 [0.0, 612],
 [-1.0, 554],
 [0.0, 617],
 [1.0, 2644],
 [0.0, 615],
 [-1.0, 556],
 [0.0, 611],
 [1.0, 2604],
 [0.0, 612],
 [-1.0, 550],
 [0.0, 607],
 [1.0, 2572],
 [0.0, 602],
 [-1.0, 543],
 [0.0, 603],
 [1.0, 2559],
 [0.0, 598],
 [-1.0, 2895],
 [0.0, 586],
 [1.0, 2529],
 [0.0, 1051],
 [-1.0, 523],
 [0.0, 582],
 [1.0, 2502],
 [0.0, 871],
 [-1.0, 528],
 [0.0, 591],
 [1.0, 2488],
 [0.0, 845],
 [-1.0, 519],
 [0.0, 580],
 [1.0, 2439],
 [0.0, 839],
 [-1.0, 518],
 [0.0, 579],
 [1.0, 2443],
 [0.0, 830],
 [-1.0, 513],
 [0.0, 572],
 [1.0, 2416],
 [0.0, 807],
 [-1.0, 508],
 [0.0, 569],
 [1.0, 2407],
 [0.0, 814],
 [-1.0, 503],
 [0.0, 560],
 [1.0, 2381],
 [0.0, 806],
 [-1.0, 498],
 [0.0, 552],
 [1.0, 2354],
 [0.0, 800],
 [-1.0, 497],
 [0.0, 555],
 [1.0, 2333],
 [0.0, 2944],
 [-1.0, 483],
 [0.0, 537],
 [1.0, 2304],
 [0.0, 5385],
 [-1.0, 563],
 [0.0, 632],
 [1.0, 2660],
 [0.0, 1116],
 [-1.0, 549],
 [0.0, 615],
 [1.0, 2629],
 [0.0, 916],
 [-1.0, 548],
 [0.0, 620],
 [1.0, 2618],
 [0.0, 2891],
 [-1.0, 545],
 [0.0, 607],
 [1.0, 2573],
 [0.0, 649],
 [-1.0, 537],
 [0.0, 605],
 [1.0, 2554],
 [0.0, 604],
 [-1.0, 540],
 [0.0, 600],
 [1.0, 2544],
 [0.0, 1091],
 [-1.0, 562],
 [0.0, 630],
 [1.0, 2662],
 [0.0, 638],
 [-1.0, 546],
 [0.0, 614],
 [1.0, 2615],
 [0.0, 646],
 [-1.0, 548],
 [0.0, 614],
 [1.0, 2604],
 [0.0, 632],
 [-1.0, 547],
 [0.0, 619],
 [1.0, 2576],
 [0.0, 629],
 [-1.0, 2909],
 [0.0, 596],
 [1.0, 2569],
 [0.0, 600],
 [-1.0, 527],
 [0.0, 599],
 [1.0, 2529],
 [0.0, 598],
 [-1.0, 533],
 [0.0, 592],
 [1.0, 2479],
 [0.0, 591],
 [-1.0, 522],
 [0.0, 589],
 [1.0, 2466],
 [0.0, 587],
 [-1.0, 522],
 [0.0, 590],
 [1.0, 2459],
 [0.0, 578],
 [-1.0, 512],
 [0.0, 579],
 [1.0, 2440],
 [0.0, 4009],
 [-1.0, 558],
 [0.0, 628],
 [1.0, 2646],
 [0.0, 614],
 [-1.0, 543],
 [0.0, 612],
 [1.0, 2603],
 [0.0, 622],
 [-1.0, 546],
 [0.0, 612],
 [1.0, 2589],
 [0.0, 615],
 [-1.0, 544],
 [0.0, 617],
 [1.0, 2565],
 [0.0, 609],
 [-1.0, 543],
 [0.0, 611],
 [1.0, 2535],
 [0.0, 2401],
 [-1.0, 528],
 [0.0, 592],
 [1.0, 2504],
 [0.0, 1088],
 [-1.0, 531],
 [0.0, 593],
 [1.0, 2473],
 [0.0, 885],
 [-1.0, 521],
 [0.0, 589],
 [1.0, 2456],
 [0.0, 862],
 [-1.0, 520],
 [0.0, 588],
 [1.0, 2461],
 [0.0, 2734],
 [-1.0, 508],
 [0.0, 570],
 [1.0, 2405],
 ...]

In [11]:
auxiliar_posicao = 0
lista_Quadrante = []
lista_final = []
numero_junto_quadrante = 4

for posicao, valor in enumerate(Tropa_do_gera):
    nova_posicao = valor[1] + auxiliar_posicao
    selected_rows = csvdata.iloc[auxiliar_posicao + 1 : nova_posicao]
    auxiliar_posicao = nova_posicao

    lista_Quadrante.append(selected_rows.copy())

    if (posicao + 1) % numero_junto_quadrante == 0:
        lista_final.append(lista_Quadrante.copy())
        lista_Quadrante = []

In [42]:
def contar_modos(Valor_modo_real):
    Tropa_do_gera = []
    qtd_contada = 0
    momento = Valor_modo_real[0] 

    for modo in range(len(Valor_modo_real)):
        if momento == Valor_modo_real[modo]:
            qtd_contada += 1
        else:
            Tropa_do_gera.append([momento, qtd_contada])
            momento = Valor_modo_real[modo]
            qtd_contada = 1 

        if modo == len(Valor_modo_real) - 1:
            Tropa_do_gera.append([momento, qtd_contada])
    
    return Tropa_do_gera

def dividir_dados(csvdata, Tropa_do_gera, numero_junto_quadrante):
    auxiliar_posicao = 0
    lista_Quadrante = []
    lista_final = []

    for posicao, valor in enumerate(Tropa_do_gera):
        nova_posicao = valor[1] + auxiliar_posicao
        selected_rows = csvdata.iloc[auxiliar_posicao : nova_posicao]
        auxiliar_posicao = nova_posicao

        lista_Quadrante.append(selected_rows.reset_index(drop=True))

        if (posicao + 1) % numero_junto_quadrante == 0:
            grupo_concatenado = pd.concat(lista_Quadrante, axis=0).reset_index(drop=True)
            lista_final.append(grupo_concatenado)
            lista_Quadrante = [] 

    if lista_Quadrante:
        grupo_concatenado = pd.concat(lista_Quadrante, axis=0).reset_index(drop=True)
        lista_final.append(grupo_concatenado)

    return lista_final

def quartificador(endereco, numero_junto_quadrante=4):
    csvdata = pd.read_csv(endereco, low_memory=False)

    csvdata = csvdata.apply(pd.to_numeric, errors='coerce')
    csvdata = csvdata.fillna(0)

    Valor_modo_real = csvdata['mode']

    Tropa_do_gera = contar_modos(Valor_modo_real)

    lista_final = dividir_dados(csvdata, Tropa_do_gera, numero_junto_quadrante)

    return lista_final

In [13]:
vetor_arquivo_geral = quartificador(r'Data\recommissioned_batteries\battery02.csv')

In [14]:

print(type(vetor_arquivo_geral))
print(vetor_arquivo_geral[0].shape)

<class 'list'>
(8202, 10)

In [15]:
vetor_arquivo_geral[0]

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
0,2022-11-26 09:49:00,0.000,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
1,2022-11-26 09:49:00,0.349,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
2,2022-11-26 09:49:00,0.496,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
3,2022-11-26 09:49:00,0.935,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
4,2022-11-26 09:49:00,1.843,0.0,8.365,22.611,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
8197,2022-11-26 09:49:00,7749.767,1.0,8.627,28.512,NaN,NaN,NaN,NaN,NaN
8198,2022-11-26 09:49:00,7750.713,1.0,8.628,28.504,NaN,NaN,NaN,NaN,NaN
8199,2022-11-26 09:49:00,7751.656,1.0,8.629,28.496,NaN,NaN,NaN,NaN,NaN
8200,2022-11-26 09:49:00,7752.599,1.0,8.630,28.492,NaN,NaN,NaN,NaN,NaN
8201,2022-11-26 09:49:00,7753.553,1.0,8.630,28.492,NaN,NaN,NaN,NaN,NaN

In [35]:
def obter_proximo_menor_valor(serie, valor_minimo):
    """Retorna o próximo menor valor da série se o valor mínimo for zero, caso contrário, retorna o valor mínimo."""
    if valor_minimo == 0:
        valores_validos = serie[serie > 0]
        if not valores_validos.empty:
            return valores_validos.min()
        else:
            return np.nan 
    return valor_minimo

def calcular_tempo_por_modo(quadrante):
    """Calcula o tempo total gasto em cada modo baseado na diferença entre tempo final e tempo inicial."""
    tempos = quadrante[['mode', 'time']]
    tempo_neutro, tempo_carga, tempo_descarga = 0, 0, 0
    
    for modo, grupo in tempos.groupby('mode'):
        if modo == 0:
            tempo_neutro = round(grupo['time'].iloc[-1] - grupo['time'].iloc[0], 2)
        elif modo == 1:
            tempo_carga += round(grupo['time'].iloc[-1] - grupo['time'].iloc[0], 2)
        elif modo == -1:
            tempo_descarga += round(grupo['time'].iloc[-1] - grupo['time'].iloc[0], 2)
    
    return tempo_neutro, tempo_carga, tempo_descarga

def calcular_vetor_quadrante(quadrante):
    tempo_neutro, tempo_carga, tempo_descarga = calcular_tempo_por_modo(quadrante)
    
    temp_max = quadrante['temperature_battery'].max()
    temp_min = obter_proximo_menor_valor(quadrante['temperature_battery'], quadrante['temperature_battery'].min())
    temp_media = quadrante['temperature_battery'].mean()
    temp_desvio_padrao = quadrante['temperature_battery'].std()
    
    if 'voltage_load' in quadrante:
        voltage_load_max = quadrante['voltage_load'].max()
        voltage_load_min = obter_proximo_menor_valor(quadrante['voltage_load'], quadrante['voltage_load'].min())
        voltage_load_media = quadrante['voltage_load'].mean()
        voltage_load_desvio = quadrante['voltage_load'].std()
    else:
        voltage_load_max = voltage_load_min = voltage_load_media = voltage_load_desvio = np.nan
    
    if 'current_load' in quadrante:
        current_load_max = quadrante['current_load'].max()
        current_load_min = obter_proximo_menor_valor(quadrante['current_load'], quadrante['current_load'].min())
        current_load_media = quadrante['current_load'].mean()
        current_load_desvio = quadrante['current_load'].std()
    else:
        current_load_max = current_load_min = current_load_media = current_load_desvio = np.nan
    
    if 'temperature_mosfet' in quadrante:
        temp_mosfet_max = quadrante['temperature_mosfet'].max()
        temp_mosfet_min = obter_proximo_menor_valor(quadrante['temperature_mosfet'], quadrante['temperature_mosfet'].min())
        temp_mosfet_media = quadrante['temperature_mosfet'].mean()
        temp_mosfet_desvio = quadrante['temperature_mosfet'].std()
    else:
        temp_mosfet_max = temp_mosfet_min = temp_mosfet_media = temp_mosfet_desvio = np.nan
    
    if 'temperature_resistor' in quadrante:
        temp_resistor_max = quadrante['temperature_resistor'].max()
        temp_resistor_min = obter_proximo_menor_valor(quadrante['temperature_resistor'], quadrante['temperature_resistor'].min())
        temp_resistor_media = quadrante['temperature_resistor'].mean()
        temp_resistor_desvio = quadrante['temperature_resistor'].std()
    else:
        temp_resistor_max = temp_resistor_min = temp_resistor_media = temp_resistor_desvio = np.nan
    
    capacidade_acumulada = (tempo_descarga / 3600) * current_load_media if tempo_descarga else np.nan

    vetor_quadrante = [
        round(tempo_neutro, 2), round(tempo_carga, 2), round(tempo_descarga, 2),
        round(temp_max, 2), round(temp_min, 2), round(temp_media, 2), round(temp_desvio_padrao, 2),
        round(voltage_load_max, 2), round(voltage_load_min, 2), round(voltage_load_media, 2), round(voltage_load_desvio, 2),
        round(current_load_max, 2), round(current_load_min, 2), round(current_load_media, 2), round(current_load_desvio, 2),
        round(temp_mosfet_max, 2), round(temp_mosfet_min, 2), round(temp_mosfet_media, 2), round(temp_mosfet_desvio, 2),
        round(temp_resistor_max, 2), round(temp_resistor_min, 2), round(temp_resistor_media, 2), round(temp_resistor_desvio, 2),
        round(capacidade_acumulada, 2)
    ]
    return vetor_quadrante

def gerar_vetores_dos_quadrantes(vetor_arquivo_geral):
    lista_vetores = []
    
    for quadrante_grupo in vetor_arquivo_geral:
        vetor_quadrante = calcular_vetor_quadrante(quadrante_grupo)
        lista_vetores.append(vetor_quadrante)
    
    return lista_vetores

In [17]:
lista_final_vetores = gerar_vetores_dos_quadrantes(vetor_arquivo_geral)

In [18]:
def remover_vetores_com_nan(lista_vetores):
    """Remove vetores que contêm valores NaN."""
    lista_filtrada = [vetor for vetor in lista_vetores if not any(np.isnan(vetor))]
    return lista_filtrada
lista_final_vetores = remover_vetores_com_nan(lista_final_vetores)

In [51]:
def processar_pasta_csv(pasta):
    lista_vetores = []
    lista_resultados = []
    
    for arquivo_csv in os.listdir(pasta):
        if arquivo_csv.endswith(".csv"):
            caminho_csv = os.path.join(pasta, arquivo_csv)
            print(caminho_csv)
            quadrantes = quartificador(caminho_csv)
            vetores_quadrantes = gerar_vetores_dos_quadrantes(quadrantes)
            vetores_filtrados = remover_vetores_com_nan(vetores_quadrantes)
            lista_vetores.extend(vetores_filtrados)

            df = pd.read_csv(caminho_csv, low_memory=False)
            ultimo_valor = df['time'].iloc[-1]
            lista_resultados.extend([ultimo_valor for x in vetores_filtrados])

    return lista_vetores, lista_resultados

In [49]:
pasta_csv = r"Data\recommissioned_batteries"
pasta_csv2 = r"Data\regular_alt_batteries"
pasta_csv3 = r"Data\second_life_batteries"

lista_final = processar_pasta_csv(pasta_csv)
lista_final2 = processar_pasta_csv(pasta_csv2)
lista_final3 = processar_pasta_csv(pasta_csv3)

for i in range(len(lista_final)):
    lista_final[i].extend(lista_final2[i])
    lista_final[i].extend(lista_final3[i])

Data\recommissioned_batteries\battery02.csv
Data\recommissioned_batteries\battery03.csv
Data\recommissioned_batteries\battery12.csv
Data\recommissioned_batteries\battery24.csv
Data\recommissioned_batteries\battery25.csv
Data\recommissioned_batteries\battery32.csv
Data\recommissioned_batteries\battery33.csv
Data\recommissioned_batteries\battery53.csv
Data\regular_alt_batteries\battery00.csv
Data\regular_alt_batteries\battery01.csv
Data\regular_alt_batteries\battery10.csv
Data\regular_alt_batteries\battery11.csv
Data\regular_alt_batteries\battery20.csv
Data\regular_alt_batteries\battery21.csv
Data\regular_alt_batteries\battery22.csv
Data\regular_alt_batteries\battery23.csv
Data\regular_alt_batteries\battery30.csv
Data\regular_alt_batteries\battery31.csv
Data\regular_alt_batteries\battery40.csv
Data\regular_alt_batteries\battery41.csv
Data\regular_alt_batteries\battery50.csv
Data\regular_alt_batteries\battery51.csv
Data\regular_alt_batteries\battery52.csv
Data\second_life_batteries\battery13.csv
Data\second_life_batteries\battery36.csv
Data\second_life_batteries\battery54.csv

In [50]:
print(f"Total de vetores finais: {len(lista_final[0])}, e {len(lista_final[1])}")

Total de vetores finais: 9883, e 9883

In [ ]:
input = len(lista_final[0][0])
saida = (0, 1)
dense_layers = [64, 32, 64]

model_mlp = create_MLP_model(input, saida, dense_layers)